name: "PHPStan"

on:
  - push
  - pull_request

permissions:
  contents: read

env:
  COMPOSER_ROOT_VERSION: dev-main

jobs:
  tests:
    name: "PHPStan"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.1"
          - latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          extensions: mongodb, redis, amqp

      - name: Add require for mongodb/mongodb to make tests runnable
        run: "composer require ${{ env.COMPOSER_FLAGS }} mongodb/mongodb --dev --no-update"

      - uses: ramsey/composer-install@a2636af0004d1c0499ffca16ac0b4cc94df70565 # 3.1.0
        with:
          dependency-versions: highest

      - name: Run PHPStan
        run: composer phpstan
